In [2]:
import pandas as pd

data = [['harry',67],['sachin',90],['nisha',34],['vicky',99]]
data


#make data frame\
pd.DataFrame(data,columns = ["Name","Marks"])

     Name  Marks
0   harry     67
1  sachin     90
2   nisha     34
3   vicky     99

In [4]:
#numpy array

import numpy as np

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

In [8]:
pd.read_csv("data.csv")

   Name   School  Marks
0  Sachin     Ad     67
1    Rama     Bl     70
2  Vikash     KS     87
3   Komal     kl     87